name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  show-vars:                  # Novo job s칩 para echos
    runs-on: ubuntu-latest
    steps:
      - name: Echo vari치vel
        env:
          MY_VARIABLE: ${{ vars.VARIABLE_TEST }}
        run: |
          echo "Valor da vari치vel: $MY_VARIABLE"
      - name: Echo secret
        env:
          MY_SECRET: ${{ secrets.SECRET_TEST }}
        run: |
          echo "Valor da secret: $MINHA_SECRET"

  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4

      - name: Build containers (frontend e backend)
        run: |
          docker compose build